server:
  port: 9001

rabbitmq:
  host: 192.168.35.175,192.168.35.3,192.168.35.65
  user: test
  password: "password"
  routingkey: test
  order:
    queue:
      buy: order.buy
      sell: order.sell
    exchange:
      buy: order.buy-exchange
      sell: order.sell-exchange
  wallet:
    queue:
      deposit: wallet.deposit
      withdraw: wallet.withdraw
    exchange:
      deposit: wallet.deposit-exchange
      withdraw: wallet.withdraw-exchange
